package view

const val UPPER_PANE_WIDTH = 1920.0
const val UPPER_PANE_HEIGHT = 162.0

const val BOTTOM_PANE_WIDTH = UPPER_PANE_WIDTH
const val BOTTOM_PANE_HEIGHT = 80.0

const val LEFT_PANE_WIDTH = 150.0
const val LEFT_PANE_HEIGHT = 838.0

const val RIGHT_PANE_WIDTH = 170.0
const val RIGHT_PANE_HEIGHT = 838.0

const val TILE_PANE_WIDTH = 8880.0
const val TILE_PANE_HEIGHT = TILE_PANE_WIDTH

const val STANDARD_TILE_VIEW_WIDTH = 120.0
const val STANDARD_TILE_VIEW_HEIGHT = 120.0


const val CENTER_TILE_PANE_POS_X = LEFT_PANE_WIDTH - TILE_PANE_WIDTH / 2 + 1600 / 2
const val CENTER_TILE_PANE_POS_Y = UPPER_PANE_HEIGHT - TILE_PANE_HEIGHT / 2 + 838 / 2


const val CENTER_POS_IN_TILE_PANE_X = TILE_PANE_WIDTH / 2 - STANDARD_TILE_VIEW_WIDTH / 2
const val CENTER_POS_IN_TILE_PANE_Y = TILE_PANE_HEIGHT / 2 - STANDARD_TILE_VIEW_HEIGHT / 2

